### ISSUE TITLE
pistar-mmdvmcal

### ISSUE THREAD

**Issue by mrickey** [AndyTaylorTweet/Pi-Star_Binaries_sbin#1]
I would like to see a script added to the sbin folder. The intent is to setup the system for running MMDVMCal.

Here are the commands I use to start MMDVMCal:

```
rpi-rw
sudo su -
systemctl stop pistar-watchdog.timer
systemctl stop pistar-watchdog
systemctl stop mmdvmhost.timer
systemctl stop mmdvmhost
cd /usr/local/bin
MMDVMCal /dev/ttyAMA0

```
It would be ideal if the port could be pulled from mmdvm.ini so the user doesn't have to figure it out. But, it would be acceptable if the user had to enter it on the command line.

Even better would be to incorporate a limited version of the MMDVMCal software into the dashboard. It would only be available for people running in repeater mode as many of the hotpots have the TX level hard coded.

**Comment by AndyTaylorTweet** [comment]
Since the MMDVMCal application is interactive, its not really possible to integrate it with the dashboard at the moment, not going to rule it out, but just not any time soon.

In the mean time 'pistar-mmdvmcal' has been added with the requested features.

**Comment by mrickey** [comment]
Thanks Andy, that will be a nice addition for repeater builders

**Comment by mrickey** [comment]
I tried this script today. The script looks to grab the first "port" in the mmdvmhost file. In my case, I have the location set to "Portable, Ca". This confuses the script a little. Maybe you could search for "Port=" instead.

**Comment by AndyTaylorTweet** [comment]
OK, see if that helps :)
