### ISSUE TITLE
iptables

### ISSUE THREAD

**Issue by f4hlv** [AndyTaylorTweet/Pi-Star_Binaries_sbin#2]
It's too bad that we can not manage the iptables rules. Can not run openvpn after an pistar-update. I use a VPN to bypass the restrictions of the 4G network.

**Comment by AndyTaylorTweet** [comment]
You *CAN* add custom firewall rules.

Add a file /root/ipv4.fw and in that file add your custom iptables lines (just the individual iptables lines - nothing else is needed); those rules are added to the firewall when the pistar-firewall script is called (every update etc).

**Comment by f4hlv** [comment]
Great, thank you for your answer.
