### ISSUE TITLE
RealVNC web access

### ISSUE THREAD

**Issue by Copper29p07** [AndyTaylorTweet/Pi-Star_Binaries_sbin#26]
I would like to VNC through their cloud to find my pi-star and remotely control it.

Are there plans to incorporate this?

I have downloaded RealVNC to the pi-star but the sudo command to start it is unfounded.

Can you help or incorporate this as a feature??

Jim

**Comment by AndyTaylorTweet** [comment]
Very unlikely, Pi-Star has no GUI, so there is nothing to VNC to on the system.

**Comment by Copper29p07** [comment]
I understand .. What is the best way to access this remotely as the MMDVM will be at a remote site with a non static IP?

**Comment by AndyTaylorTweet** [comment]
If you have a router that supports Dynamic DNS, this is a good option, or you could look into a VPN solution, there are probably a lot of different ways to solve it depending on what you have available.

Andy
