### ISSUE TITLE
pistar-bmapi needs update

### ISSUE THREAD

**Issue by bejoysat** [AndyTaylorTweet/Pi-Star_Binaries_sbin#48]
The script figures out wrong DMRID when parsing /etc/mmdvmhost, causing the final command to BM API to fail.

`DMRNetHost=$(sed -n -e '/\[DMR Network\]/,/\[System Fusion Network\]/p' /etc/mmdvmhost | grep "Address=" | awk -F "=" '/Address=/ {print $2}')
if [[ "${DMRNetHost}" == "127.0.0.1" ]]; then
`

Above command returns two lines, which is not expected by the if statement. The new mmdvmhost.ini contains RemoteAddress and LocalAddress values for DMR Network.

**Comment by MW0MWZ** [comment]
fixed
