### ISSUE TITLE
pistar-vyehsflash fails

### ISSUE THREAD

**Issue by plughplover** [AndyTaylorTweet/Pi-Star_Binaries_sbin#55]
I'm kinda flailing around here, because I can't figure out who "owns" what...

"MW0MWZ" made the most recent changes to this script,
https://github.com/AndyTaylorTweet/Pi-Star_Binaries_sbin/commits/master/pistar-vyehsflash
but it CAN'T work because of

https://github.com/VR2VYE/MMDVM_HS_firmware/issues/3
(which I posted almost a month ago)

i.e. "install_fw_nanohs.sh" is not part of https://github.com/VR2VYE/MMDVM_HS_firmware/releases/latest

**Comment by MW0MWZ** [comment]
install_fw_nanohs.sh was part of the distribution, but it no longer is. I assume there is no more support for flashing anything other than the duplex versions. I can remove that option.

**Comment by MW0MWZ** [comment]
For reference - here in an older build that DID include it: https://github.com/VR2VYE/MMDVM_HS_firmware/releases/tag/v1.4.17

**Comment by plughplover** [comment]
Well, my employer has 100 units he imported that aren't working :(

"MMDVM_HS firmware from CA6JAU" - a-ha! 
So @juribparada is CA6JAU who is the author/maintainer of the MMDVM_HS STM MCU (arduino) fw?
(As I stated at the beginning, I don't know who "owns" what piece here)

Well, at this point I'm trying to circuit trace the modem board to get https://github.com/juribeparada/STM32F10X_Lib to talk to the F103C8T6 on it (I always get 'Failed to init device.')  
So far I've established the mcu BOOT0 pin is connected to PG8 on the NEO (aka GPIO 200) thru a resistor, next up is to trace the NRST pin (to NEO PA3 aka GPIO 3, I think).
Once I get stm32flash talking to the mcu i'll try both the ca6jau and vr2vye fw files and see if they address my problem.

**Comment by plughplover** [comment]
I noticed that install_fw_nanohs.sh on juribparada master branch had a section at the top (that wasn't in the version in his v1.5.2 asset list) that twiddled gpio 3 with echo commands.

I was able to get stm32flash to talk to the mcu by doing this
echo 3 > /sys/class/gpio/export
then
echo out > /sys/class/gpio/gpio3/direction
echo 1 > /sys/class/gpio/gpio3/value
sudo ./STM32F10X_Lib/utils/rpi32/stm32flash -r ./raw_fw -g 0x0 -R -i "200,-3,3:-200,3" /dev/ttyAMA0

Next up: try out those two fw files...

**Comment by plughplover** [comment]
Sigh... Neither fw file addressed my original issue. Back to the drawing board...

FYI, I noticed a time element to getting stm32flash to work. If a few seconds elapsed between
echo 1 > /sys/class/gpio/gpio3/value
and the actual stm32flash command, it would 'fail to init device'. A tweak to the sequence to
echo 3 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio3/direction
then
sudo ./STM32F10X_Lib/utils/rpi32/stm32flash -g 0x0 -R -i "3,200,-3,3:-200,3" /dev/ttyAMA0
(note the extra 3 in the -i param) seemed to eliminate the time window. 
FWIW YMMV

**Comment by plughplover** [comment]
PS -
the high address written with the ca6jau fw was 0x0800c6b4
the high address written with the vr2vye fw was 0x0800cb98
ie vr2vye fw is 1,252 bytes larger

**Comment by MW0MWZ** [comment]
What was the original problem, not sure you mentioned it.

**Comment by plughplover** [comment]
See back in the middle of (https://github.com/VR2VYE/MMDVM_HS_firmware/issues/3), where I say
**Why am I trying to update the firmware?**

**Comment by plughplover** [comment]
FWIW by writing fw, reading back, and binary compares, I've established that this batch of units has

https://github.com/juribeparada/MMDVM_HS/releases/download/v1.5.2/mmdvm_hs_hat_fw.bin
installed rather than
https://github.com/juribeparada/MMDVM_HS/releases/download/v1.5.2/nano_hotspot_fw.bin
or
https://github.com/VR2VYE/MMDVM_HS_firmware/releases/download/v1.5.2/nano_hotspot_fw.bin

However, as I stated above, neither of the nano_hotspot_fw files addressed my problem.

**Comment by plughplover** [comment]
Sigh... Just to be sure, I wired the NPi hat to my mmdvm_hs Rpi Zero W, and the issue followed the hat.
Found this on the net, which proved helpful...
![Nano_hotSPOT_GPIO_Definition](https://user-images.githubusercontent.com/8658014/202930756-73257701-10ec-474e-8877-af8c0ec44705.png)

**Comment by MW0MWZ** [comment]
When you looked at the spectrum scope, is the output on frequency?

**Comment by plughplover** [comment]
Wasn't looking for accuracy, just presence. Used a TinySA. The HT also shows it is detecting signal.

Tried tweaking "TXOffset" ± a couple hundred, and tried bumping TXLevel up to 60. No apparent effect (but can't find docs).
Playing with pistar trace/debug/file level/etc settings don't seem to do anything (lack of docs again).

Started reading the datasheet on the ADF7021, but can't find any obvious test points on the board. (I do have an ancient HP logic analyzer that I haven't booted in a decade - floppies are probably shot).

Found some references to using RTLSDR dongle (I have one) and some GNU Radio stuff (would need to build a Linux box) to capture / examine the emitted signal(s). Might go that route, as then maybe I could compare Rpi hat signal to Npi hat signal, 

Getting discouraged, probably going to take the week off...

**Comment by evgeny-mezin-epam** [comment]
@plughplover managed to fix the issue by manually doing the following:

Logged into SSH of my pi-star
```
sudo su 
cd /tmp
curl -OL https://raw.githubusercontent.com/VR2VYE/MMDVM_HS_firmware/master/install_fw_nanohs.sh
```
changed the path to binary in script from
`https://github.com/juribeparada/MMDVM_HS/releases/download/$FW_VERSION/nano_hotspot_fw.bin`
to
`https://github.com/VR2VYE/MMDVM_HS_firmware/releases/download/v1.5.2/nano_hotspot_fw.bin`

Stopped all services
```
sudo pistar-watchdog.service stop
sudo systemctl stop mmdvmhost.timer
sudo systemctl stop mmdvmhost.service
sudo killall MMDVMHost >/dev/null 2>&1
```
Started the script
`./install_fw_nanohs.sh`

**Comment by evgeny-mezin-epam** [comment]
@AndyTaylorTweet Definitely there should be a way to fix it permanently in Pi-Star assemblies as well

**Comment by plughplover** [comment]
FYI - My 'week off' (above) turned into more like 3 months lol, 
but I have every intention of restarting my hw diagnostic efforts 'soon'. 

However, that's going to be separate from *this* issue. 

(I think I'll start a thread in the pistar forum on *that* rather than taking this thread further off topic.)
